// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwp7M4dEfKtDtW0EBKFSy6fOtdGUi9CcA',
    appId: '1:421924305521:web:df4c5cc7009bb94da079d0',
    messagingSenderId: '421924305521',
    projectId: 'car-app-410f4',
    authDomain: 'car-app-410f4.firebaseapp.com',
    storageBucket: 'car-app-410f4.appspot.com',
    measurementId: 'G-19M733XJHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPjr72rUH8Bw-GyCs5rME1xbRwLokbws4',
    appId: '1:421924305521:android:e0f1e2a17ffff1e1a079d0',
    messagingSenderId: '421924305521',
    projectId: 'car-app-410f4',
    storageBucket: 'car-app-410f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8-404x65EgRao5G24RSeX00Ei5UsdEUY',
    appId: '1:421924305521:ios:f1fcc20e20be548fa079d0',
    messagingSenderId: '421924305521',
    projectId: 'car-app-410f4',
    storageBucket: 'car-app-410f4.appspot.com',
    iosClientId: '421924305521-tqpdni12as64c458jrkvf4l8043768kr.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoOasis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8-404x65EgRao5G24RSeX00Ei5UsdEUY',
    appId: '1:421924305521:ios:b3da7f46dea2e3e6a079d0',
    messagingSenderId: '421924305521',
    projectId: 'car-app-410f4',
    storageBucket: 'car-app-410f4.appspot.com',
    iosClientId: '421924305521-cpbvv2ck3caa4i1mvbo89lmo14r7ksd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoOasis.RunnerTests',
  );
}
